server:
  port: 8080
#h2 db on memory
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    show-sql: true
#    hibernate.ddl-auto: update
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: false
      
          
spring:
  datasource:
    url: jdbc:mysql://srvdbclientes:3306/testdb?useSSL=false
    username: root
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate.ddl-auto: update
      
      